<?php
namespace App\Core;

/**
 * Web Push API & VAPID Dispatcher Service
 * news-platform / src / Core / WebPush.php
 * 
 * Implements:
 * - RFC 8292: Voluntary Application Server Identification (VAPID) for Web Push
 * - RFC 8291: Message Encryption for Web Push (aes128gcm)
 * - RFC 8030: Generic Event Delivery Using Web Push
 */

use App\Core\Database;
use Exception;
use RuntimeException;
use Throwable;

class WebPush
{
    private static ?array $config = null;

    /**
     * Ensure OpenSSL configuration file is set for Windows PHP environments
     */
    private static function getOpenSslConfPath(): ?string
    {
        $current = getenv('OPENSSL_CONF');
        if ($current && file_exists($current)) {
            return $current;
        }

        $candidates = [
            'C:/xampp/apache/bin/openssl.cnf',
            'C:/xampp/apache/conf/openssl.cnf',
            'C:/xampp/php/extras/openssl/openssl.cnf',
            'C:/xampp/php/extras/ssl/openssl.cnf',
            'C:/xampp/php/openssl.cnf'
        ];

        foreach ($candidates as $candidate) {
            if (file_exists($candidate)) {
                putenv("OPENSSL_CONF={$candidate}");
                return $candidate;
            }
        }
        return null;
    }

    /**
     * Load or automatically generate VAPID configuration
     */
    public static function getConfig(): array
    {
        if (self::$config !== null) {
            return self::$config;
        }

        $configFile = __DIR__ . '/../../config/vapid.php';

        if (file_exists($configFile)) {
            $loaded = require $configFile;
            if (is_array($loaded) && !empty($loaded['public_key']) && !empty($loaded['private_key'])) {
                self::$config = $loaded;
                return self::$config;
            }
        }

        // Auto-generate VAPID keys if missing
        $cnf = self::getOpenSslConfPath();
        $keyOptions = [
            'curve_name' => 'prime256v1',
            'private_key_type' => OPENSSL_KEYTYPE_EC
        ];
        if ($cnf) {
            $keyOptions['config'] = $cnf;
        }
        $key = @openssl_pkey_new($keyOptions);

        if (!$key) {
            throw new RuntimeException('Failed to generate VAPID EC keypair: ' . openssl_error_string());
        }

        $details = openssl_pkey_get_details($key);
        $publicKeyRaw = "\x04" . $details['ec']['x'] . $details['ec']['y'];
        $privateKeyRaw = $details['ec']['d'];

        $config = [
            'public_key'  => self::base64UrlEncode($publicKeyRaw),
            'private_key' => self::base64UrlEncode($privateKeyRaw),
            'subject'     => 'mailto:alerts@newsplatform.local',
        ];

        $localConfigFile = __DIR__ . '/../../config/vapid.local.php';
        $phpContent = "<?php\n/**\n * Web Push VAPID Keys (Local Override)\n * Auto-generated by NewsPlatform CMS\n */\nreturn " . var_export($config, true) . ";\n";
        @file_put_contents($localConfigFile, $phpContent);

        self::$config = $config;
        return self::$config;
    }

    /**
     * Get the VAPID Public Key for client browser subscription
     */
    public static function getPublicKey(): string
    {
        $cfg = self::getConfig();
        return $cfg['public_key'] ?? '';
    }

    /**
     * Get the VAPID Subject string
     */
    public static function getSubject(): string
    {
        $cfg = self::getConfig();
        return $cfg['subject'] ?? 'mailto:alerts@newsplatform.local';
    }

    /**
     * Register or update a browser push subscription in the database
     */
    public static function subscribe(string $endpoint, string $p256dh, string $auth, ?int $readerId = null, ?string $userAgent = null): bool
    {
        $endpoint = trim($endpoint);
        $p256dh = trim($p256dh);
        $auth = trim($auth);

        if (empty($endpoint) || empty($p256dh) || empty($auth)) {
            return false;
        }

        $endpointHash = hash('sha256', $endpoint);
        $db = Database::getInstance();

        $existing = $db->fetch("SELECT id FROM push_subscriptions WHERE endpoint_hash = :hash", ['hash' => $endpointHash]);

        if ($existing) {
            $db->execute(
                "UPDATE push_subscriptions 
                 SET p256dh = :p256dh, auth = :auth, reader_id = :reader_id, user_agent = :ua 
                 WHERE id = :id",
                [
                    'p256dh' => $p256dh,
                    'auth' => $auth,
                    'reader_id' => $readerId,
                    'ua' => $userAgent ? mb_substr($userAgent, 0, 250) : null,
                    'id' => $existing['id']
                ]
            );
        } else {
            $db->execute(
                "INSERT INTO push_subscriptions (endpoint, endpoint_hash, p256dh, auth, reader_id, user_agent, created_at)
                 VALUES (:endpoint, :hash, :p256dh, :auth, :reader_id, :ua, NOW())",
                [
                    'endpoint' => $endpoint,
                    'hash' => $endpointHash,
                    'p256dh' => $p256dh,
                    'auth' => $auth,
                    'reader_id' => $readerId,
                    'ua' => $userAgent ? mb_substr($userAgent, 0, 250) : null
                ]
            );
        }

        return true;
    }

    /**
     * Remove a browser push subscription
     */
    public static function unsubscribe(string $endpoint): bool
    {
        $endpointHash = hash('sha256', trim($endpoint));
        $db = Database::getInstance();
        return $db->execute("DELETE FROM push_subscriptions WHERE endpoint_hash = :hash", ['hash' => $endpointHash]);
    }

    /**
     * Dispatch Breaking News Web Push Notification to all subscribed devices
     */
    public static function sendBreakingNewsNotification(int $articleId, string $title, string $summary, string $slug): array
    {
        $articleUrl = url('article.php?slug=' . urlencode($slug));
        $iconUrl = url('assets/icons/icon-192.png');
        $badgeUrl = url('assets/icons/icon-192.png');

        $payload = [
            'title' => '🚨 ' . __('breaking') . ': ' . $title,
            'body' => mb_substr(strip_tags($summary), 0, 180),
            'icon' => $iconUrl,
            'badge' => $badgeUrl,
            'tag' => 'breaking-news-' . $articleId,
            'data' => [
                'url' => $articleUrl,
                'article_id' => $articleId,
                'is_breaking' => true,
                'timestamp' => time()
            ]
        ];

        return self::sendToAll($payload);
    }

    /**
     * Broadcast payload to all opted-in push subscriptions
     */
    public static function sendToAll(array $payload): array
    {
        $db = Database::getInstance();
        $subscriptions = $db->fetchAll("SELECT * FROM push_subscriptions ORDER BY id DESC");

        $results = [
            'total' => count($subscriptions),
            'success' => 0,
            'failed' => 0,
            'pruned' => 0
        ];

        if (empty($subscriptions)) {
            return $results;
        }

        $payloadJson = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $pruneIds = [];

        foreach ($subscriptions as $sub) {
            try {
                $status = self::sendPush($sub, $payloadJson);

                if ($status >= 200 && $status < 300) {
                    $results['success']++;
                    $db->execute("UPDATE push_subscriptions SET last_notified_at = NOW() WHERE id = :id", ['id' => $sub['id']]);
                } elseif ($status === 404 || $status === 410) {
                    // Subscription expired or unregistered by client browser
                    $pruneIds[] = (int)$sub['id'];
                    $results['failed']++;
                } else {
                    $results['failed']++;
                }
            } catch (Throwable $e) {
                error_log('[WebPush] Error sending notification to sub ID ' . $sub['id'] . ': ' . $e->getMessage());
                $results['failed']++;
            }
        }

        // Clean up expired subscriptions
        if (!empty($pruneIds)) {
            $inClause = implode(',', $pruneIds);
            $db->execute("DELETE FROM push_subscriptions WHERE id IN ({$inClause})");
            $results['pruned'] = count($pruneIds);
        }

        return $results;
    }

    /**
     * Send encrypted push notification via cURL
     */
    public static function sendPush(array $subscription, string $payloadJson): int
    {
        $endpoint = $subscription['endpoint'];
        $clientPubKeyB64 = $subscription['p256dh'];
        $clientAuthB64 = $subscription['auth'];

        $parsedUrl = parse_url($endpoint);
        if (!$parsedUrl || !isset($parsedUrl['scheme'], $parsedUrl['host'])) {
            return 400;
        }

        $origin = $parsedUrl['scheme'] . '://' . $parsedUrl['host'];
        if (isset($parsedUrl['port'])) {
            $origin .= ':' . $parsedUrl['port'];
        }

        $config = self::getConfig();
        $jwt = self::createVapidJwt($origin, $config);

        // Encrypt message according to RFC 8291 (aes128gcm)
        $encrypted = self::encryptPayload($payloadJson, $clientPubKeyB64, $clientAuthB64);

        $headers = [
            'Content-Type: application/octet-stream',
            'Content-Encoding: aes128gcm',
            'TTL: 86400',
            'Urgency: high',
            'Authorization: vapid t=' . $jwt . ', k=' . $config['public_key']
        ];

        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL => $endpoint,
            CURLOPT_POST => true,
            CURLOPT_POSTFIELDS => $encrypted,
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 15,
            CURLOPT_SSL_VERIFYPEER => true
        ]);

        curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        if (\PHP_VERSION_ID < 80000 && function_exists('curl_close')) {
            @call_user_func('curl_close', $ch);
        }

        return (int)$httpCode;
    }

    /**
     * Encrypt JSON payload using RFC 8291 (aes128gcm)
     */
    private static function encryptPayload(string $payloadJson, string $clientPublicKeyB64, string $clientAuthB64): string
    {
        self::getOpenSslConfPath();

        $clientPubKey = self::base64UrlDecode($clientPublicKeyB64);
        $clientAuth = self::base64UrlDecode($clientAuthB64);

        // 1. Generate local ephemeral EC key pair
        $cnf = self::getOpenSslConfPath();
        $keyOptions = [
            'curve_name' => 'prime256v1',
            'private_key_type' => OPENSSL_KEYTYPE_EC
        ];
        if ($cnf) {
            $keyOptions['config'] = $cnf;
        }
        $serverKey = @openssl_pkey_new($keyOptions);

        if (!$serverKey) {
            throw new RuntimeException('Failed to generate ephemeral EC key: ' . openssl_error_string());
        }

        $serverDetails = openssl_pkey_get_details($serverKey);
        $serverPubKey = "\x04" . $serverDetails['ec']['x'] . $serverDetails['ec']['y'];

        // 2. Convert client public key to PEM and compute ECDH shared secret
        $clientDer = pack('H*', '3059301306072a8648ce3d020106082a8648ce3d030107034200') . $clientPubKey;
        $clientPem = "-----BEGIN PUBLIC KEY-----\n" . chunk_split(base64_encode($clientDer), 64, "\n") . "-----END PUBLIC KEY-----\n";
        $clientKeyResource = openssl_pkey_get_public($clientPem);

        if (!$clientKeyResource) {
            throw new RuntimeException('Invalid client public key: ' . openssl_error_string());
        }

        $ecdhSecret = openssl_pkey_derive($clientKeyResource, $serverKey, 32);
        if (!$ecdhSecret) {
            throw new RuntimeException('ECDH secret derivation failed.');
        }

        // 3. RFC 8291 Key Derivation using HKDF
        $salt = random_bytes(16);
        $prkKey = hash_hmac('sha256', $ecdhSecret, $clientAuth, true);
        $info = "WebPush: info\x00" . $clientPubKey . $serverPubKey;
        $ikm = hash_hkdf('sha256', $prkKey, 32, $info, '');

        $cek = hash_hkdf('sha256', $ikm, 16, "Content-Encoding: aes128gcm\x00", $salt);
        $nonce = hash_hkdf('sha256', $ikm, 12, "Content-Encoding: nonce\x00", $salt);

        // 4. Pad payload with \x02 delimiter (RFC 8188 single record)
        $paddedPayload = $payloadJson . "\x02";

        $tag = '';
        $ciphertext = openssl_encrypt($paddedPayload, 'aes-128-gcm', $cek, OPENSSL_RAW_DATA, $nonce, $tag);
        if ($ciphertext === false) {
            throw new RuntimeException('AES-GCM encryption failed: ' . openssl_error_string());
        }

        // 5. Construct RFC 8188 binary body:
        // salt (16 bytes) || record size (4 bytes = 4096 = \x00\x00\x10\x00) || idlen (1 byte = 65 = \x41) || serverPubKey (65 bytes) || ciphertext || tag (16 bytes)
        $recordSize = pack('N', 4096);
        $idLen = chr(strlen($serverPubKey));

        return $salt . $recordSize . $idLen . $serverPubKey . $ciphertext . $tag;
    }

    /**
     * Generate VAPID ES256 Signed JWT
     */
    private static function createVapidJwt(string $aud, array $config): string
    {
        self::getOpenSslConfPath();

        $header = self::base64UrlEncode(json_encode(['typ' => 'JWT', 'alg' => 'ES256']));
        $claims = self::base64UrlEncode(json_encode([
            'aud' => $aud,
            'exp' => time() + 86400,
            'sub' => $config['subject'] ?? 'mailto:alerts@newsplatform.local'
        ]));
        $data = $header . '.' . $claims;

        $privRaw = self::base64UrlDecode($config['private_key']);
        $pubRaw = self::base64UrlDecode($config['public_key']);

        // DER EC Private Key Structure (RFC 5915)
        $der = "\x30\x77\x02\x01\x01\x04\x20" . $privRaw . "\xa0\x0a\x06\x08\x2a\x86\x48\xce\x3d\x03\x01\x07\xa1\x44\x03\x42\x00" . $pubRaw;
        $pem = "-----BEGIN EC PRIVATE KEY-----\n" . chunk_split(base64_encode($der), 64, "\n") . "-----END EC PRIVATE KEY-----\n";

        $privKeyResource = openssl_pkey_get_private($pem);
        if (!$privKeyResource) {
            throw new RuntimeException('Failed to load VAPID private key into OpenSSL: ' . openssl_error_string());
        }

        $signatureDer = '';
        if (!openssl_sign($data, $signatureDer, $privKeyResource, OPENSSL_ALGO_SHA256)) {
            throw new RuntimeException('Failed to sign VAPID JWT: ' . openssl_error_string());
        }

        $rawSignature = self::derToRawSignature($signatureDer);
        return $data . '.' . self::base64UrlEncode($rawSignature);
    }

    /**
     * Convert ASN.1 DER signature to IEEE P1363 (r || s, 64 bytes)
     */
    private static function derToRawSignature(string $der): string
    {
        $pos = 0;
        if (ord($der[$pos++]) !== 0x30) return '';
        $len = ord($der[$pos++]);
        if ($len & 0x80) {
            $bytes = $len & 0x7f;
            $pos += $bytes;
        }
        if (ord($der[$pos++]) !== 0x02) return '';
        $rlen = ord($der[$pos++]);
        $r = substr($der, $pos, $rlen);
        $pos += $rlen;

        if (ord($der[$pos++]) !== 0x02) return '';
        $slen = ord($der[$pos++]);
        $s = substr($der, $pos, $slen);

        $r = ltrim($r, "\x00");
        $s = ltrim($s, "\x00");
        $r = str_pad($r, 32, "\x00", STR_PAD_LEFT);
        $s = str_pad($s, 32, "\x00", STR_PAD_LEFT);
        return $r . $s;
    }

    public static function base64UrlEncode(string $data): string
    {
        return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
    }

    public static function base64UrlDecode(string $data): string
    {
        return base64_decode(strtr($data, '-_', '+/') . str_repeat('=', (4 - strlen($data) % 4) % 4));
    }
}
